name: music-transcription
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  
  - pip
  - tensorflow 
  - pip:
      - streamlit
      - "basic-pitch[tf]"
      - audio-recorder-streamlit